export const categoryOptions = [
    { value: "cerealsBeans", label: "Cereals and Beans", id: "1" },
    { value: "milkYogurts", label: "Milk and yogurt (1,5-2%)", id: "2" },
    { value: "sweetsSnacks", label: "Sweets and snacks", id: "3" },
    { value: "proteins", label: "Proteins", id: "4" },
    { value: "vegetables", label: "Vegetables (incl. canned)", id: "5" },
    { value: "fatsSauces", label: "Fats and Sauces", id: "6" },
    { value: "dairy", label: "Dairy", id: "7" },
    { value: "fruits", label: "Fruits", id: "8" },
    { value: "nuts", label: "Nuts and seeds", id: "9" },
];

export const productOptions = [
    {
        value: "beans",
        label: "Beans",
        limitGramm: "100",
        id: "1",
        categoryId: "1",
    },
    {
        value: "potatoes",
        label: "Potatoes",
        limitGramm: "360",
        id: "2",
        categoryId: "1",
    },
    {
        value: "fresh corn",
        label: "Fresh Corn",
        limitGramm: "360",
        id: "3",
        categoryId: "1",
    },
    {
        value: "cereal",
        label: "Cereal",
        limitGramm: "100",
        id: "4",
        categoryId: "1",
    },
    {
        value: "bulgur",
        label: "Bulgur",
        limitGramm: "100",
        id: "5",
        categoryId: "1",
    },
    {
        value: "buckwheat",
        label: "Buckwheat",
        limitGramm: "80",
        id: "6",
        categoryId: "1",
    },
    {
        value: "unpolished rice",
        label: "Unpolished Rice",
        limitGramm: "100",
        id: "7",
        categoryId: "1",
    },
    {
        value: "any groats",
        label: "Any Groats",
        limitGramm: "100",
        id: "8",
        categoryId: "1",
    },
    {
        value: "whole grain flour",
        label: "Whole Grain Flour",
        limitGramm: "100",
        id: "9",
        categoryId: "1",
    },
    {
        value: "crispbread",
        label: "Crispbread",
        limitGramm: "160",
        id: "10",
        categoryId: "1",
    },
    {
        value: "whole grain bread",
        label: "Whole Grain Bread",
        limitGramm: "170",
        id: "11",
        categoryId: "1",
    },
    {
        value: "whole wheat pasta",
        label: "Whole Wheat Pasta",
        limitGramm: "100",
        id: "12",
        categoryId: "1",
    },
    {
        value: "lavash",
        label: "Lavash",
        limitGramm: "160",
        id: "13",
        categoryId: "1",
    },
    {
        value: "diary",
        label: "Diary (1,5-2%)",
        limitGramm: "200",
        id: "1",
        categoryId: "2",
    },
    {
        value: "sweetsSnacks",
        label: "Sweets and snacks",
        limitGramm: "55",
        id: "2",
        categoryId: "3",
    },
    {
        value: "beef",
        label: "Beef",
        limitGramm: "320",
        id: "1",
        categoryId: "4",
    },
    {
        value: "liver",
        label: "Liver",
        limitGramm: "320",
        id: "2",
        categoryId: "4",
    },
    {
        value: "chickenTurkey",
        label: "Chicken/Turkey fillet",
        limitGramm: "380",
        id: "3",
        categoryId: "4",
    },
    {
        value: "fishLowFat",
        label: "Fish <= 5% fat",
        limitGramm: "370",
        id: "4",
        categoryId: "4",
    },
    {
        value: "fishFat",
        label: "Fish > 5% fat",
        limitGramm: "250",
        id: "5",
        categoryId: "4",
    },
    { value: "eggs", label: "Eggs", limitGramm: "6", id: "6", categoryId: "4" },
    {
        value: "seafood",
        label: "Seafood",
        limitGramm: "440",
        id: "7",
        categoryId: "4",
    },
    {
        value: "vegetables",
        label: "Vegetables (incl. canned)",
        limitGramm: "600",
        id: "1",
        categoryId: "5",
    },
    { value: "oil", label: "Oil", limitGramm: "24", id: "1", categoryId: "6" },
    {
        value: "avocado",
        label: "Avocado",
        limitGramm: "130",
        id: "2",
        categoryId: "6",
    },
    {
        value: "olives",
        label: "Olives",
        limitGramm: "160",
        id: "3",
        categoryId: "6",
    },
    {
        value: "mustard",
        label: "Mustard",
        limitGramm: "56",
        id: "4",
        categoryId: "6",
    },
    {
        value: "mayonnaise",
        label: "Mayonnaise",
        limitGramm: "30",
        id: "5",
        categoryId: "6",
    },
    {
        value: "ketchup",
        label: "Ketchup",
        limitGramm: "84",
        id: "6",
        categoryId: "6",
    },
    {
        value: "cottageCheese",
        label: "Cottage cheese 5%",
        limitGramm: 160,
        id: "1",
        categoryId: "7",
    },
    {
        value: "cheeses",
        label: "Soft, hard, processed cheeses",
        limitGramm: 55,
        id: "2",
        categoryId: "7",
    },
    {
        value: "sourCream",
        label: "Sour cream 15%",
        limitGramm: 110,
        id: "3",
        categoryId: "7",
    },
    {
        value: "butter",
        label: "Butter",
        limitGramm: 27,
        id: "4",
        categoryId: "7",
    },
    { value: "salo", label: "Salo", limitGramm: 19, id: "5", categoryId: "7" },
    {
        value: "kefir",
        label: "Kefir 2.5%",
        limitGramm: 360,
        id: "6",
        categoryId: "7",
    },
    {
        value: "yogurt",
        label: "Unsweetened yogurt 1.6%",
        limitGramm: 370,
        id: "7",
        categoryId: "7",
    },
    {
        value: "milkDairy",
        label: "Milk 2.5%",
        limitGramm: 360,
        id: "8",
        categoryId: "7",
    },
    {
        value: "fruits1",
        label: "Fruits, berries EXCEPT bananas, grapes, persimmons, mango",
        limitGramm: 300,
        id: "1",
        categoryId: "8",
    },
    {
        value: "fruits2",
        label: "Bananas, grapes, persimmons, mango",
        limitGramm: 180,
        id: "2",
        categoryId: "8",
    },
    {
        value: "walnuts",
        label: "Walnuts",
        limitGramm: 3,
        id: "1",
        categoryId: "9",
    },
    {
        value: "nutsSeeds",
        label: "Other nuts or seeds",
        limitGramm: 20,
        id: "2",
        categoryId: "9",
    },
];
